services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - "conscioux-network"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - "conscioux-network"
    env_file: 
      - path: ".env"
        required: true
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - "conscioux-network"

networks:
  "conscioux-network":
    driver: bridge

