version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - "conscioux-network"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - "conscioux-network"
    env_file: 
      - path: ".env"
        required: true

networks:
  "conscioux-network":
    driver: bridge

